const response = {
  correct: [
    "Nice one pre, Tama!",
    "Lupet mo naman, pwede ka na mag board",
    "Luh! Gusto mo mag top no?!",
    "Taena, di ka na yata natutulog e",
    "Siguro sa Elements ka lang magaling",
    // "Pwede mo na palitan si Sir Deyn",
    "Tsamba HAHAHAHA",
    "Gagi!!! Pano mo nalaman yon???",
    "Tama ka na naman, mag asawa ka na kaya?",
    "Sana maalala mo to sa boards",
    "Nanghula na nga lang tama pa, lakas Guardian Angel",
    "Babae ka ba? Bakit tama ka?",
    // "Pag sinabi kong ES sabihin niyo?????",
    "Payag? Payag",
    "Wag puro Looksfam tol",
  ],
  incorrect: [
    "HAHAHAHA TANGA",
    "Luh, Parang di nag Grade 2",
    "Pati sa Elements mali ka? Nakakahiya",
    "Paalala lang: Inom ka water. LABYU <3",
    "Kaka ML mo yan, tangek",
    "Ay di to pwede mag Engineer",
    "Para kang lizard sa kisame",
    "Calculate mo kasi kahit Elements",
    "OOHH DIBAAAA? NAKAKAPUT******",
    "Kulang pa sa review, Tara shot",
    "Mali ka naman, pereng tenge enebe hehehe",
    "Yan hula hula pa, Buti nga sayo!",
    "Si Gloc9 walang apelyido, Ikaw walang Tinama",
    "Baka gutom lang yan",
  ],
};

export default response;
